spring.application.name=user-service
server.port=8082

spring.datasource.url=${USER_DB_URL:jdbc:postgresql://localhost:5434/secureops_user}
spring.datasource.username=${USER_DB_USERNAME:secureops}
spring.datasource.password=${USER_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info