services:

  auth-db:
    image: postgres:17
    container_name: secureops-auth-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-secureops_auth}
      POSTGRES_USER: ${POSTGRES_USER:-secureops}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - auth-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-secureops} -d ${POSTGRES_DB:-secureops_auth}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth-db-data: