spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/secureops_auth
spring.datasource.username=secureops
spring.datasource.password=secureops_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info